[package]
name = "upload"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
humansize = "2.1.3"
once_cell = "1.19.0"
rocket = "0.5.1"

[profile.release]
lto = "fat"
strip = true
codegen-units = 1
panic = "abort"
